runmode: debug                 # 开发模式, debug, release, test
addr: :8081                 # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1:8081   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
# 日志配置
log:
  writers: file,stdout # 输出位置
  logger_level: DEBUG
  logger_file: log/apiserver.log # 日志文件
  log_format_text: false # true为非json格式，false为json格式
  rollingPolicy: size # size按大小进行转存，daily为按天进行转存
  log_rotate_date: 1 # 转存时间 配合daily
  log_rotate_size: 1 # 转存大小 配合size MB
  log_backup_count: 7 # 当日志文件达到转存标准时，log 系统会将该日志文件进行压缩备份，这里指定了备份文件的最大个数
